import type { Recipe } from "./types";

export const recipes: Recipe[] = [
  {
    title: "Cajun Chicken Risotto",
    description:
      "Spicy chicken risotto with sautéed capsicum, celery and onion.",
    slug: "cajun-chicken-risotto",
    macros: [
      { title: "Cals", value: 513 },
      { title: "Protein", value: 51 },
      { title: "Carbs", value: 60 },
      { title: "Fats", value: 9 },
    ],
    servings: 5,
    ingredients: [
      "Chicken breast (1 kg)",
      "Salt (2 tsp)",
      "Black pepper (2 tsp)",
      "Smoked paprika (2 tsp)",
      "Garlic (3 cloves - minced)",
      "Dried oregano (1tsp)",
      "Lemon zest (1/2 lemon)",
      "Worcestershire sauce (2 tsp)",
      "Chilli powder (1/3 tsp)",
      "",
      "Brown onion (250g & diced how ever fine or coarse you want)",
      "Red Capsicum (250g diced how ever fine or coarse you want)",
      "Celery (250g diced how ever fine or coarse you want)",
      "Garlic (3 cloves - minced)",
      "Salt (1/2 tsp)",
      "Black pepper (1/2 tsp)",
      "",
      "Jasmine rice (300 g)",
      "Can diced tomatoes (400 g)",
      "Chicken stock (450 g)",
    ],
    method: [
      "Dice the chicken breasts into small, bite sized pieces, then place in a mixing bowl. Add a touch of olive oil and season with all of the listed seasonings. Mix well, then let marinate for however long you want.",
      'Sear the chicken in a 12" frying pan (I ended up doing two batches.) with some olive oil until cooked through. Place in a bowl and set to the side.',
      "In the same pan, add some olive oil, add all of your diced veggies with your salt and cook until nice and caramelised. Toss in your minced garlic.",
      "Add your rice and let toast for a minute before adding in your can of diced tomatoes and chicken stock. Simmer until the rice is cooked.",
    ],
  },
  {
    title: "Spicy Chicken & Sweet Potatoes",
    description: "Spicy chicken & sweet potatoes",
    slug: "spicy-chicken-sweet-potato",
    macros: [
      { title: "Cals", value: 453 },
      { title: "Protein", value: 58 },
      { title: "Carbs", value: 42 },
      { title: "Fats", value: 5 },
    ],
    servings: 5,
    ingredients: [
      "Chicken breast (850 g)",
      "Salt (2 tsp)",
      "Black pepper (2 tsp)",
      "Smoked paprika (2 tsp)",
      "Chilli powder (2 tsp)",
      "Cumin (1 tsp)",
      "Garlic (3 cloves - minced)",
      "Lemon juice (wedge)",
      "",
      "Sweet potatoes (1.5 kg)",
      "Salt (2 tsp)",
      "Black pepper (2 tsp)",
      "Garlic powder (2 tsp)",
    ],
    method: [
      "Put chicken breasts, glug of olive oil, salt, pepper, smoked paprika, chilli powder, cumin, garlic cloves and a squeeze of a lemon wedge into a bowl and let marinate for how ever long you want.",
      "Pre-heat oven to 230°C. Cut the sweet potatoes into wedges, place them on a baking tray and season with salt, pepper, garlic powder & olive oil. Bake until cooked through.",
      'To cook the chicken, add some oil to a 12" frying pan and sear until there is some beautiful colour. Chuck into the oven to finish the chicken until reached 75°C.',
      "To serve, slice the chicken against the grain otherwise it'll be a tough as anything in the mouth and add some potatoes.",
    ],
  },
];
